type User {
  id: ID!
  username: String!
  rooms: [ChatRoom!]!
}

type ChatRoom {
  id: ID!
  name: String!
  timestamp: String!
  owner: User!
  members: [User!]!
  lastMessages: [ChatMessage!]!
}

type ChatMessage {
  id: ID!
  room: ChatRoom!
  timestamp: String!
  author: User!
  text: String!
}

type Query {
  register(username: String!, password: String!): User
  login(username: String!, password: String!): String!
  me: User
  users: [User!]!
  rooms: [ChatRoom!]!
}

type Mutation {
  createRoom(name: String!): ChatRoom!
  deleteRoom(id: ID!): ChatRoom
}

type Subscription {
  roomCreated: ChatRoom
  roomDeleted: ChatRoom
  messageCreated: ChatMessage
}